package com.entity;

/**
 * City generated by MyEclipse Persistence Tools
 */

public class City implements java.io.Serializable {

	// Fields

	private Integer cid;

	private Province province;

	private String cname;

	// Constructors

	/** default constructor */
	public City() {
	}

	/** full constructor */
	public City(Province province, String cname) {
		this.province = province;
		this.cname = cname;
	}

	// Property accessors

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

}