package com.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by MyEclipse Persistence Tools
 */

public class Province implements java.io.Serializable {

	// Fields

	private Integer pid;

	private String pname;

	private Set cities = new HashSet(0);

	// Constructors

	/** default constructor */
	public Province() {
	}

	/** minimal constructor */
	public Province(String pname) {
		this.pname = pname;
	}

	/** full constructor */
	public Province(String pname, Set cities) {
		this.pname = pname;
		this.cities = cities;
	}

	// Property accessors

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public Set getCities() {
		return this.cities;
	}

	public void setCities(Set cities) {
		this.cities = cities;
	}

}